"""widen campaign_engagements event_type

Revision ID: 03f9321bc316
Revises: f21a1a0238ce
Create Date: 2026-07-23 16:59:18.854829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03f9321bc316'
down_revision = 'f21a1a0238ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_engagements', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_engagements', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
