"""Add contacts, contact_lists, email_campaigns, campaign_runs

Revision ID: 12320e456be3
Revises: ee026485877a
Create Date: 2026-07-16 14:14:26.896551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12320e456be3'
down_revision = 'ee026485877a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_lists',
    sa.Column('brevo_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_lists_brevo_list_id'), ['brevo_list_id'], unique=True)

    op.create_table('contacts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('last_webhook_event', sa.String(length=40), nullable=True),
    sa.Column('classified_by_id', sa.String(length=36), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_classified_by_id'), ['classified_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=True)

    op.create_table('email_campaigns',
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('brevo_campaign_id', sa.Integer(), nullable=True),
    sa.Column('contact_list_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('content_file_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('cta_links', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('email_content', sa.Text(), nullable=True),
    sa.Column('is_generating', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=20), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_campaigns_brevo_campaign_id'), ['brevo_campaign_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_campaigns_contact_list_id'), ['contact_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_campaigns_created_by_id'), ['created_by_id'], unique=False)

    op.create_table('campaign_runs',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('brevo_campaign_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_runs_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_runs_campaign_id'))

    op.drop_table('campaign_runs')
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_campaigns_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_email_campaigns_contact_list_id'))
        batch_op.drop_index(batch_op.f('ix_email_campaigns_brevo_campaign_id'))

    op.drop_table('email_campaigns')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_classified_by_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_lists_brevo_list_id'))

    op.drop_table('contact_lists')
    # ### end Alembic commands ###
