"""Replace test_emails.label with name

Revision ID: 4b5980412770
Revises: 7783b581d467
Create Date: 2026-07-16 15:42:47.996961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b5980412770'
down_revision = '7783b581d467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=160), nullable=True))
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
