"""empty message

Revision ID: 61d7e4a0aa86
Revises: 4b5980412770
Create Date: 2026-07-20 18:06:49.057313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61d7e4a0aa86'
down_revision = '4b5980412770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.alter_column('brevo_campaign_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.alter_column('brevo_campaign_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
