"""Add test_emails

Revision ID: 7783b581d467
Revises: 12320e456be3
Create Date: 2026-07-16 15:35:31.972610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7783b581d467'
down_revision = '12320e456be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_emails',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('added_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_emails_added_by_id'), ['added_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_emails_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_emails_email'))
        batch_op.drop_index(batch_op.f('ix_test_emails_added_by_id'))

    op.drop_table('test_emails')
    # ### end Alembic commands ###
