"""add campaign_engagements table

Revision ID: f21a1a0238ce
Revises: 61d7e4a0aa86
Create Date: 2026-07-23 16:53:33.842595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21a1a0238ce'
down_revision = '61d7e4a0aa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_engagements',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_engagements_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_engagements_contact_email'), ['contact_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_engagements_contact_email'))
        batch_op.drop_index(batch_op.f('ix_campaign_engagements_campaign_id'))

    op.drop_table('campaign_engagements')
    # ### end Alembic commands ###
